export const CONFIDENCE_LEVELS = ["LOW", "MEDIUM", "HIGH"];
export const ASSUMPTION_CATEGORIES = ["DESIRABILITY", "VIABILITY", "FEASIBILITY", "USABILITY"];
export const VALIDATION_STATES = ["SUPPORTS", "WEAKENS", "FALSIFIES", "INCONCLUSIVE"];
export const LIFECYCLE_STAGES = ["DISCOVERED", "TRIANGULATED", "VALIDATED", "INSTITUTIONALIZED", "OBSOLETE"];
export const PRIVACY_LEVELS = ["PUBLIC", "INTERNAL", "RESTRICTED"];
export const RELATIONSHIP_TYPES = ["OUTCOME_OPPORTUNITY", "OPPORTUNITY_SOLUTION", "SOLUTION_ASSUMPTION", "NODE"];
export const EXPERIMENT_STATUSES = ["PLANNED", "RUNNING", "COMPLETE", "ARCHIVED"];

export const DEFAULT_PAGE_SIZE = 25;
